# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "h:/IDE14_7/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "J:/zing_pro/snowleo/SnowLeo_SDR_v14_7_rls2.0_int/pldma.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "j:/zing_pro/snowleo/SnowLeo_SDR_v14_7_rls2.0_int/pldma.srcs/sources_1/ip/chipscope_ila_v1_05_a_0/coregen.cgc"

set ipFile "j:/zing_pro/snowleo/SnowLeo_SDR_v14_7_rls2.0_int/pldma.srcs/sources_1/ip/chipscope_ila_v1_05_a_0/ila_v1_05_a_0.xco"

set ipName "ila_v1_05_a_0"

set hdlType "Verilog"

set cgPartSpec "xc7z010-1clg400"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "j:/zing_pro/snowleo/SnowLeo_SDR_v14_7_rls2.0_int/pldma.srcs/sources_1/ip/chipscope_ila_v1_05_a_0/pa_cg_bom.xml"

# generate the IP
set result [source "h:/IDE14_7/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

