# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "h:/IDE14_7/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "J:/zing_pro/snowleo/SnowLeo_SDR_v14_7_rls2.0_int/pldma.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "j:/zing_pro/snowleo/SnowLeo_SDR_v14_7_rls2.0_int/pldma.srcs/sources_1/ip/clk_wiz_v3_6_2/coregen.cgc"

set ipFile "j:/zing_pro/snowleo/SnowLeo_SDR_v14_7_rls2.0_int/pldma.srcs/sources_1/ip/clk_wiz_v3_6_2/clk_wiz_v3_6_2.xco"

set ipName "clk_wiz_v3_6_2"

set hdlType "Verilog"

set cgPartSpec "xc7z020-1clg400"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "j:/zing_pro/snowleo/SnowLeo_SDR_v14_7_rls2.0_int/pldma.srcs/sources_1/ip/clk_wiz_v3_6_2/pa_cg_bom.xml"

# generate the IP
set result [source "h:/IDE14_7/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

