# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories true

set tclUtilsPath "e:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "D:/my_work/Zing-project/SnowLeo_SDR_v14_7_rls2.0_int_7020_src/pldma.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "d:/my_work/Zing-project/SnowLeo_SDR_v14_7_rls2.0_int_7020_src/pldma.srcs/sources_1/ip/clk_wiz_v3_6_2/coregen.cgc"

set ipFile "d:/my_work/Zing-project/SnowLeo_SDR_v14_7_rls2.0_int_7020_src/pldma.srcs/sources_1/ip/clk_wiz_v3_6_2/clk_wiz_v3_6_2.xco"

set ipName "clk_wiz_v3_6_2"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "d:/my_work/Zing-project/SnowLeo_SDR_v14_7_rls2.0_int_7020_src/pldma.srcs/sources_1/ip/clk_wiz_v3_6_2/pa_cg_bom.xml"

set cgPartSpec "xc7z020-1clg400"

set hdlType "Verilog"

# generate the IP
set result [source "e:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

