######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

proc _main_ {} {
  cd "J:/zing_pro/snowleo/SnowLeo_SDR_v14_7_rls2.0_int/pldma.srcs/sources_1/edk/cpu0"
  if { [ catch {xload xmp cpu0.xmp} result ] } {
    exit 10
  }
  xset arch zynq
  xset dev xc7z020
  xset package clg400
  xset speedgrade -1

xset binfo 

  save proj
  return $result
}

# Execute set part
if { [catch {_main_} result] } {
  exit -1
}

# Check return status and exit
if { [string length $result] == 0 } {
  exit 0
} else {
  exit $result
}
